BLOG_Salesforce/force-apps/deploy/main/default/objects/FunnyName__c/FunnyName__c.object-meta.xml
<CustomObject>
    <label>Funny Name</label>
    <nameField>
        <label>Funny Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funny Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BLOG_Salesforce/force-apps/deploy/main/default/objects/FunnyName__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

BLOG_Salesforce/force-apps/deploy/main/default/objects/FunnyName__c/fields/Pronunciation__c.field-meta.xml
<CustomField>
    <fullName>Pronunciation__c</fullName>
    <label>Pronunciation</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BLOG_Salesforce/force-apps/deploy/main/default/objects/FunnyName__c/fields/Random__c.field-meta.xml
<CustomField>
    <fullName>Random__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Random</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

BLOG_Salesforce/force-apps/deploy/main/default/classes/GetFunnyName.cls
@RestResource(urlMapping='/GetFunnyName/v1')
global with sharing class GetFunnyName {
	@AuraEnabled(cacheable=true)
	public static FunnyName__c lwc(Id recordId) {
		return data(recordId);
	}

	@HttpPost
	global static FunnyName__c post(Id recordId) {
		return data(recordId);
	}

	private static FunnyName__c data(Id recordId) {
		FunnyName__c output = null;

		try {
			if (recordId != null) {
				output = [SELECT Id, Name, Points__c, Pronunciation__c, Random__c FROM FunnyName__c WHERE Id = :recordId];
			}
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
		return output;
	}
}