BLOG_Salesforce/force-apps/deploy/main/default/objects/FunnyName__c/FunnyName__c.object-meta.xml
<CustomObject>
    <label>Funny Name</label>
    <nameField>
        <label>Funny Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funny Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BLOG_Salesforce/force-apps/deploy/main/default/objects/FunnyName__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

BLOG_Salesforce/force-apps/deploy/main/default/objects/FunnyName__c/fields/Pronunciation__c.field-meta.xml
<CustomField>
    <fullName>Pronunciation__c</fullName>
    <label>Pronunciation</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

BLOG_Salesforce/force-apps/deploy/main/default/objects/FunnyName__c/fields/Random__c.field-meta.xml
<CustomField>
    <fullName>Random__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Random</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

BLOG_Salesforce/force-apps/deploy/main/default/classes/GetTopRecords.cls
@RestResource(urlMapping='/GetTopRecords/v1')
global with sharing class GetTopRecords {
	@AuraEnabled(cacheable=true)
	public static List<FunnyName__c> lwc(Integer howMany) {
		return data(howMany);
	}

	@HttpPost
	global static List<FunnyName__c> post(Integer howMany) {
		return data(howMany);
	}

	private static List<FunnyName__c> data(Integer howMany) {
		try {
			return [SELECT Id, Name, Points__c, Pronunciation__c, Random__c FROM FunnyName__c ORDER BY Random__c DESC LIMIT :howMany];
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}
}